# Generated by Django 5.2.7 on 2025-10-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_like_options_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='like',
            name='unique_like_per_user_per_post',
            constraint=models.UniqueConstraint(fields=('post', 'username'), name='unique_like_per_user_per_post', violation_error_code='LIKE_ALREADY_EXISTS', violation_error_message='You have already liked this post.'),
        ),
    ]
